name: HTML Validator

on: [push, pull_request]

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Klona repot
        uses: actions/checkout@v3

      - name: Installera HTMLHint
        run: |
          npm install -g htmlhint
          htmlhint HTML_CSS/index.html
