name: Python Tests

on: [push, pull_request]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installera Python och kör tester
        run: |
          python3 -m unittest discover -s . -p "test_*.py"
