name: Python Linter

on: [push, pull_request]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installera Python och flake8
        run: |
          sudo apt-get install -y python3-pip
          pip install flake8
          flake8 Python/hello.py
